#PROD environment
server:
    port: 8080
app:
    message: This is the property file to the ${spring.application.name} specific to PRODUCTION Environment
spring:
    datasource: 
        drive-class-name: com.mysql.cj.jdbc.Driver
        url: <MYSQL_URL>
        username: <USERNAME>
        password: <PASSWORD>